extends: coverage_common.yaml
policy:
  name: custom
  custom: zr10lab.algorithms.optimal_reference:OptimalReferencePolicy
  algorithm_id: opt
  opt_time_limit_s: 60.0
  opt_max_viewpoints_per_device: 10
